### ISSUE TITLE
Feature request: Toggle between Rabbithole mode and CLI generator mode

### ISSUE THREAD

**Issue by dot-Justin** [dot-Justin/LAMatHome#19]
**Describe the integration you'd like**
- Let user decide if they want to pull entries from RH or via CLI, then parse based on that

**Additional context**
- Potentially use a generator
- Potentially store "CLI_MODE" in .env, or explore options other than .env for general config

**Comment by pnivek** [comment]
https://github.com/dot-Justin/LAMatHome/compare/main...cli-mode

**Comment by pnivek** [comment]
feature has been added, along with a config where all program settings are stored. closing issue.
