### ISSUE TITLE
Enhancement request: Prompt Suggestion

### ISSUE THREAD

**Issue by KenTheWhaleGoddess** [dot-Justin/LAMAtHome#27]
**From ChatGPT**

The prompt you provided [from llm_parse.py of this repo] is quite detailed and long. For a repeatable process, especially if you need to run it frequently, it might be beneficial to streamline and condense it. Here are a few suggestions to make it more manageable:

- Condense Repeated Instructions: Combine similar instructions to reduce redundancy. For example, many examples demonstrate similar concepts (missing variables, unclear commands).

- Utilize Abbreviations and Short Forms: Use shorter forms where possible without losing clarity.

- External Documentation: Move some detailed explanations and examples to an external document that you can reference, keeping the main prompt focused on essential instructions.

- Hierarchical Structure: Organize the information hierarchically with clear headings, so it’s easier to parse visually and programmatically.

**Here's a more condensed version of your prompt:**
```
## System Instructions for Command Recognition

# Integration List:

# Computer Commands:

- Google: "Computer Google [search query]"
- YouTube: "Computer YouTube [search query]"
- Gmail: "Computer Gmail [search query]"
- Amazon: "Computer Amazon [search query]"
- Volume: "Computer Volume [1-100|up|down|mute|unmute]"
- Run: "Computer run [search term]"

# Messaging Commands:
- Telegram: "Telegram [Name] [Message]"
- Discord: "Discord [Name] [Message]"
- Facebook: "Facebook [Name] [Message]"

# Alias:

- Lam at Home / Lamb at Home = lamathome
- Terminate: "lamathome terminate"

# Instructions:

- For missing platform/recipient/message, respond with "x".
- For unlisted commands, respond with "x".
- For multiple commands, chain with "&&". Ignore invalid commands in chaining.
- For general knowledge questions, respond with "x".
- No placeholders or user interactions.

# Examples:
- "Telegram Jason" → "x" (Missing Message)
- "Message John" → "x" (Missing Platform, Message)
- "Send a message to Justin on WhatsApp" → "x" (Unlisted service)
- "Telegram Jason What's on the shopping list?" → "Telegram Jason What's on the shopping list?"
```

**Comment by dot-Justin** [comment]
Thanks for opening this up @KenTheWhaleGoddess!
I will run some tests and look into the effects of having a shorter prompt, but in all honesty I think it will degrade performance.

Additionally, since we're requesting a *new* chat completion each time a journal entry is logged, the instructions are always fresh in the LLM's "mind".

If using the [Groq API](https://console.groq.com/keys) like we do, you will have no issues with rate limits. With my testing over the past few days you can run a one prompt every 0.8 seconds and not get rate limited, which is faster than you can even send prompts to r1 haha.

Thanks again, will look into this.

**Comment by KenTheWhaleGoddess** [comment]
I think my takeaways were
- (Seemingly to me) fewer filler words
- Alias section for key words "Terminate, Lam at Home"
- Examples section is more standardized (with parentheses for the X reasoning)

**Comment by KenTheWhaleGoddess** [comment]
My intention with opening is to improve* the result of the one-shot prompt, copy all that about the API limits/new chat however. 

*improve just in the context of processing/answering questions that are in the scope of its SW capabilities.

**Comment by pnivek** [comment]
We tried the prompt and the performance was substantially worse on our suite of tests. Closing PR.

**Comment by dot-Justin** [comment]
For reference:
The current prompt in the main branch (which I call prompt_v2.4) only failed 1 out of 100 test prompts.
However, with this new, shorter prompt, failed 19 out of the same 100 test prompts.

Thank you for the suggestion nonetheless! We will continue to strive for new ways to improve LAMatHome.
