### ISSUE TITLE
Question/Suggestion: Potential answer to longer than 24 hour Access Token

### ISSUE THREAD

**Issue by RobErskine** [dot-Justin/LAMatHome#33]
**Question/Suggestion**
So I haven't tried to set up your project yet, I am actually working on my own thing trying to sync journal entries to my own application, but that is besides the point. 

I was also scratching my head trying to figure out a way around the 24 hour expire token on the sessionId and accessKey token, and I think I am onto something that I wanted to share and get your thoughts. I originally went trying to figure out how to get the CAPTCHA working with the oauth login route, but I don't think there is a way around that.

Then I thought about extending the expire time past the 24 hour mark. You can't update the expire time in the client via the browser, but you can do it from the server. I noticed that whenever you interact with your profile inside the rabbit hole, your session token renews.

**One easy way to POST/PATCH to rabbit is by updating your name with `updateUserProfile`, pass it your current access token and your new name, then re-inspect your `appToken` cookie in the application panel, and notice that it has been refreshed to the currentTime + 24 hours!**
![Arc-Journal_2024-06-06 at 22 52@2x](https://github.com/dot-Justin/LAMatHome/assets/1895120/c13d375e-ac2f-49ee-b24d-5fc3f8f29b20)

```
2024-06-07T22:34:22.921Z | Before I left to run errands, eat dinner, and hangout for a bit

2024-06-08T02:52:26.535Z | When I came back to send this update
```

I am going to try my hand at this tomorrow after work, but wanted to get the wheels turning with other folks who have been looking for a workaround.

**Additional context**
- You don't actually need to change the value of your `profile.name`, so you could just keep submitting ` { profile: { name: 'Rob' } }` over and over, and your token will be refreshed.

**Comment by dot-Justin** [comment]
Interesting stuff, assigning @pnivek on this.
Thanks for sharing!

**Comment by glovergaytan-fs** [comment]
oooh? very nice. 

single sign in would be perfect. then i could run indefinitely

**Comment by pnivek** [comment]
Hey @RobErskine. I was taking a look and for the cookie, I don't actually see an attribute named `appToken`. Did you mean `appSession`? If so I noticed the `Expires / Max-Age` attribute refreshes even when you reload the journal page. After updating my profile to a new name I was logged out not too long after and had to sign back in so I had some doubts about this. Can you confirm?

**Comment by RobErskine** [comment]
@pnivek Yeah apologies I meant `appSession`. I may have jumped the gun with this solution; I can confirm I am seeing the same functionality on my end. 

I'm working on a [Raycast](https://raycast.com) extension to get rabbit hole journal entries and I wrote a no-view command that updates the profile name every 4 hours to keep a user logged in. After testing this over the weekend it doesn't seem to have any effect on the user token that the API requires, so the `appSession` expire time doesn't seem to be connected.

Back to the drawing board I suppose. I'll keep my eyes out for any other ways to get around this. 

![Arc-QuestionSuggestion Potential answer to longer than 24 hour Access Token · Issue #33 · dot-JustinLAMatHome_2024-06-10 at 10 52@2x](https://github.com/dot-Justin/LAMatHome/assets/1895120/95a6ecf3-05d7-4399-b635-e08b594b2c8e)
