### ISSUE TITLE
Bug: LAH is trying to run notepad instead of Notion

### ISSUE THREAD

**Issue by KiyanLalani** [dot-Justin/LAMatHome#45]
**Describe the bug**
When giving the R1 a prompt to run notion on a computer, it searches for notepad instead

**To Reproduce**
"Run Notion on my computer"

**Expected behavior**
Notion was meant to be opened on the computer instead of notepad

**Screenshots**
2024-06-10 10:09:19 - INFO - Prompt: Run Notion on my computer.
2024-06-10 10:09:21 - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2024-06-10 10:09:21 - INFO - Full response from Groq API: ChatCompletion(id='chatcmpl-a5bf5736-61b2-493f-ba60-4b0f53072718', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Computer run Notepad', role='assistant', function_call=None, tool_calls=None))], created=1718010561, model='llama3-70b-8192', object='chat.completion', system_fingerprint='fp_753a4aecf6', usage=CompletionUsage(completion_tokens=4, prompt_tokens=2416, total_tokens=2420, completion_time=0.012090019, prompt_time=1.189132916, queue_time=None, total_time=1.2012229349999999), x_groq={'id': 'req_01j00phfcgfwpbk71dcrhfesxy'})
2024-06-10 10:09:21 - INFO - Response text: Computer run Notepad
2024-06-10 10:09:21 - INFO - Task: Computer run Notepad
command is: notepad

**Environment (please complete the following information):**
 - MacOS Sonoma
 - Python Version: 3.12.3

**Comment by pnivek** [comment]
@glovergaytan-fs they are on mac so it gave an error since there is no notepad

**Comment by dot-Justin** [comment]
@pnivek @glovergaytan-fs Could be a prompting issue, I think it just doesn't know that it's a mac. Maybe when we run llm_parse we include the platform variable as well so it knows which apps do and dont exist.

**Comment by KiyanLalani** [comment]
> > @dot-Justin are you saying you think the llm decided that notepad was the closest match to notion and ignored the literal? strange.
> 
> 
> 
> I guess so, not quite sure what happened.
> 
> @KiyanLalani Can you confirm if this was reproducible?

I tried a few more times after making the bug report and the same error persisted. I noticed that it was working fine on the branch google-home but not on the main branch. I have not tried again yet

**Comment by dot-Justin** [comment]
> > > @dot-Justin are you saying you think the llm decided that notepad was the closest match to notion and ignored the literal? strange.
> > 
> > 
> > I guess so, not quite sure what happened.
> > @KiyanLalani Can you confirm if this was reproducible?
> 
> I tried a few more times after making the bug report and the same error persisted. I noticed that it was working fine on the branch google-home but not on the main branch. I have not tried again yet

Very interesting. Have you `git pull`ed since then? google-home has been merged with main, plus other changes. I've been doing some testing with the same prompts and haven't had the same issue, but I'm not on mac. Though, that shouldn't matter since the LLM Parsing function doesn't yet know what platform the user is on. I will continue doing some testing and let you know what I find out.

**Comment by KiyanLalani** [comment]
> > I tried a few more times after making the bug report and the same error persisted. I noticed that it was working fine on the branch google-home but not on the main branch. I have not tried again yet
> 
> 
> 
> Very interesting. Have you `git pull`ed from main since then? google-home has been merged with main, plus other changes. I've been doing some testing with the same prompts and haven't had the same issue, but I'm not on mac. Though, that shouldn't matter since the LLM Parsing function doesn't yet know what platform the user is on. I will continue doing some testing and let you know what I find out.

I haven't tried since the two branches have been merged. I'll have a chance to try again a bit later and I'll make sure to tell you the results

**Comment by dot-Justin** [comment]
> I haven't tried since the two branches have been merged. I'll have a chance to try again a bit later and I'll make sure to tell you the results

Appreciate you, will keep an eye out!

**Comment by KiyanLalani** [comment]
> > I haven't tried since the two branches have been merged. I'll have a chance to try again a bit later and I'll make sure to tell you the results
> 
> 
> 
> Appreciate you, will keep an eye out!
Okay, so it doesn't seem to be a problem anymore. Not sure what happened those first few times but everything works perfectly now

**Comment by KiyanLalani** [comment]
> > Okay, so it doesn't seem to be a problem anymore. Not sure what happened those first few times but everything works perfectly now
> 
> 
> 
> Perfect. Glad it's working for you now! If you run into this again, please feel free to re-open and we'll investigate further.

Thank you
