### ISSUE TITLE
Integration request: Facebook Messenger

### ISSUE THREAD

**Issue by dot-Justin** [dot-Justin/LAMAtHome#7]
**Describe the integration you'd like**
- Just like telegram

**Potential syntax for your integration**
- ditto, "Messenger [user] [message]"

**Website URL to automate (or thing to be locally automated)**
- https://www.messenger.com/
  
**Additional context**
- n/a

**Comment by glovergaytan-fs** [comment]
few more checks and balances and it will be ready

**Comment by pnivek** [comment]
V1 change to include include facebook messenger was merged to main, closing this one.
